import type { SiteCopyDefinition } from "@/lib/site-copy-definitions";

/** Editable transactional email copy (admin → Content → Emails). */
export const EMAIL_COPY_DEFINITIONS: SiteCopyDefinition[] = [
  {
    group: "Emails — shared header",
    key: "email.brand.title",
    label: "Brand name in email header",
    format: "plain",
    defaultValue: "Recchi Studio",
  },
  {
    group: "Emails — shared header",
    key: "email.brand.tagline",
    label: "Tagline under brand name",
    format: "plain",
    defaultValue: "Nature-inspired patterns & apparel",
  },

  {
    group: "Emails — contact alert (to you)",
    key: "email.contact.subject",
    label: "Subject line",
    format: "plain",
    defaultValue: "Recchi Studio contact ({topic}): {name}",
  },
  {
    group: "Emails — contact alert (to you)",
    key: "email.contact.eyebrow",
    label: "Small label above headline",
    format: "plain",
    defaultValue: "Contact form",
  },
  {
    group: "Emails — contact alert (to you)",
    key: "email.contact.title",
    label: "Main headline",
    format: "plain",
    defaultValue: "New message",
  },
  {
    group: "Emails — contact alert (to you)",
    key: "email.contact.from_label",
    label: "Row label — sender",
    format: "plain",
    defaultValue: "From",
  },
  {
    group: "Emails — contact alert (to you)",
    key: "email.contact.topic_label",
    label: "Row label — topic",
    format: "plain",
    defaultValue: "Topic",
  },
  {
    group: "Emails — contact alert (to you)",
    key: "email.contact.garment_label",
    label: "Row label — garment (custom/bulk orders)",
    format: "plain",
    defaultValue: "Garment",
  },
  {
    group: "Emails — contact alert (to you)",
    key: "email.contact.quantity_label",
    label: "Row label — quantity (custom/bulk orders)",
    format: "plain",
    defaultValue: "Quantity",
  },
  {
    group: "Emails — contact alert (to you)",
    key: "email.contact.deadline_label",
    label: "Row label — deadline (custom/bulk orders)",
    format: "plain",
    defaultValue: "Deadline",
  },
  {
    group: "Emails — contact alert (to you)",
    key: "email.contact.reference_images_label",
    label: "Section label — reference images",
    format: "plain",
    defaultValue: "Reference images",
  },
  {
    group: "Emails — contact alert (to you)",
    key: "email.contact.message_label",
    label: "Section label — customer's message",
    format: "plain",
    defaultValue: "Message",
  },

  {
    group: "Emails — new order (to you)",
    key: "email.order.subject",
    label: "Subject line",
    format: "plain",
    defaultValue: "New order: {productName}",
  },
  {
    group: "Emails — new order (to you)",
    key: "email.order.eyebrow",
    label: "Small label above headline",
    format: "plain",
    defaultValue: "New order",
  },
  {
    group: "Emails — new order (to you)",
    key: "email.order.title",
    label: "Main headline",
    format: "plain",
    defaultValue: "You have a new order",
  },
  {
    group: "Emails — new order (to you)",
    key: "email.order.item_label",
    label: "Table column — item",
    format: "plain",
    defaultValue: "Item",
  },
  {
    group: "Emails — new order (to you)",
    key: "email.order.qty_label",
    label: "Table column — quantity",
    format: "plain",
    defaultValue: "Qty",
  },
  {
    group: "Emails — new order (to you)",
    key: "email.order.amount_label",
    label: "Table column — amount",
    format: "plain",
    defaultValue: "Amount",
  },
  {
    group: "Emails — new order (to you)",
    key: "email.order.total_label",
    label: "Table row — total",
    format: "plain",
    defaultValue: "Total",
  },
  {
    group: "Emails — new order (to you)",
    key: "email.order.customer_label",
    label: "Row label — customer name",
    format: "plain",
    defaultValue: "Customer",
  },
  {
    group: "Emails — new order (to you)",
    key: "email.order.email_label",
    label: "Row label — customer email",
    format: "plain",
    defaultValue: "Email",
  },
  {
    group: "Emails — new order (to you)",
    key: "email.order.shipping_label",
    label: "Row label — shipping address",
    format: "plain",
    defaultValue: "Shipping",
  },
  {
    group: "Emails — new order (to you)",
    key: "email.order.stripe_label",
    label: "Row label — Stripe session ID",
    format: "plain",
    defaultValue: "Stripe session",
  },

  {
    group: "Emails — quote ready (to customer)",
    key: "email.quote.subject",
    label: "Subject line",
    format: "plain",
    defaultValue: "Your Recchi Studio quote is ready",
  },
  {
    group: "Emails — quote ready (to customer)",
    key: "email.quote.eyebrow",
    label: "Small label above headline",
    format: "plain",
    defaultValue: "Quote ready",
  },
  {
    group: "Emails — quote ready (to customer)",
    key: "email.quote.greeting",
    label: "Main headline / greeting",
    format: "plain",
    defaultValue: "Hi {customerName},",
  },
  {
    group: "Emails — quote ready (to customer)",
    key: "email.quote.intro",
    label: "Intro paragraph",
    format: "plain",
    defaultValue: "Your {topic} quote from Recchi Studio is ready.",
  },
  {
    group: "Emails — quote ready (to customer)",
    key: "email.quote.total_label",
    label: "Label above quoted amount",
    format: "plain",
    defaultValue: "Quoted total",
  },
  {
    group: "Emails — quote ready (to customer)",
    key: "email.quote.details_label",
    label: "Section label — quote notes",
    format: "plain",
    defaultValue: "Details",
  },
  {
    group: "Emails — quote ready (to customer)",
    key: "email.quote.followup",
    label: "Closing paragraph",
    format: "plain",
    defaultValue:
      "Reply to this email or get in touch if you would like to proceed or have any questions.",
  },
  {
    group: "Emails — quote ready (to customer)",
    key: "email.quote.cta_label",
    label: "Button label",
    format: "plain",
    defaultValue: "Contact us",
  },
];
